export enum ROLE {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  USER = 'USER',
}

export enum GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum ROLE_SCOPE {
  SYSTEM = 'SYSTEM',
  ORGANIZATION = 'ORGANIZATION',
}

export enum ORGANIZATION_ROLE {
  HR_ADMIN = 'HR_ADMIN',
  HR_STAFF = 'HR_STAFF',
  INTERVIEWER = 'INTERVIEWER',
}

export enum JOB_STATUS {
  DRAFT = 'DRAFT',
  OPENING = 'OPENING',
  CLOSED = 'CLOSED',
  CANCELED = 'CANCELED',
}

export enum EMPLOYMENT_TYPE {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  TEMPORARY = 'TEMPORARY',
  INTERNSHIP = 'INTERNSHIP',
}
